package fst5.example.demo;

import java.time.LocalDate;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Entity class representing a customer.
 *
 * <p>
 * This class is mapped to the customer table in the database
 * using Hibernate/JPA.
 * </p>
 */
@Entity
@Table(name = "customer")
public class Customer {

    /**
     * Unique ID of the customer.
     *
     * <p>
     * The ID is automatically generated by the database.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * First name of the customer.
     */
    private String firstName;

    /**
     * Last name of the customer.
     */
    private String lastName;

    /**
     * Date of birth of the customer.
     */
    private LocalDate dateOfBirth;

    /**
     * Mobile number of the customer.
     */
    private String mobile;

    /**
     * First address of the customer.
     */
    private String address1;

    /**
     * Second address of the customer.
     */
    private String address2;

    /**
     * Age of the customer.
     */
    private int age;

    /**
     * Gender of the customer.
     */
    private String gender;

    /**
     * Email address of the customer.
     */
    private String email;

    /**
     * Default constructor required by JPA.
     */
    public Customer() {
    }

    /**
     * Parameterized constructor used to create a Customer object
     * with all customer details.
     *
     * @param firstName   customer's first name
     * @param lastName    customer's last name
     * @param dateOfBirth customer's date of birth
     * @param mobile      customer's mobile number
     * @param address1    customer's first address
     * @param address2    customer's second address
     * @param age         customer's age
     * @param gender      customer's gender
     * @param email       customer's email address
     */
    public Customer(String firstName,
            String lastName,
            LocalDate dateOfBirth,
            String mobile,
            String address1,
            String address2,
            int age,
            String gender,
            String email) {

        this.firstName = firstName;
        this.lastName = lastName;
        this.dateOfBirth = dateOfBirth;
        this.mobile = mobile;
        this.address1 = address1;
        this.address2 = address2;
        this.age = age;
        this.gender = gender;
        this.email = email;
    }

    /**
     * Returns the customer ID.
     *
     * @return customer ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the customer ID.
     *
     * @param id customer ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the customer's first name.
     *
     * @return first name
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the customer's first name.
     *
     * @param firstName first name
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Returns the customer's last name.
     *
     * @return last name
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the customer's last name.
     *
     * @param lastName last name
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Returns the customer's date of birth.
     *
     * @return date of birth
     */
    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the customer's date of birth.
     *
     * @param dateOfBirth date of birth
     */
    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * Returns the customer's mobile number.
     *
     * @return mobile number
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * Sets the customer's mobile number.
     *
     * @param mobile mobile number
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * Returns the customer's first address.
     *
     * @return address 1
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * Sets the customer's first address.
     *
     * @param address1 first address
     */
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    /**
     * Returns the customer's second address.
     *
     * @return address 2
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * Sets the customer's second address.
     *
     * @param address2 second address
     */
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    /**
     * Returns the customer's age.
     *
     * @return age
     */
    public int getAge() {
        return age;
    }

    /**
     * Sets the customer's age.
     *
     * @param age age
     */
    public void setAge(int age) {
        this.age = age;
    }

    /**
     * Returns the customer's gender.
     *
     * @return gender
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the customer's gender.
     *
     * @param gender gender
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * Returns the customer's email address.
     *
     * @return email address
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the customer's email address.
     *
     * @param email email address
     */
    public void setEmail(String email) {
        this.email = email;
    }
}