package fst5.example.demo.entity;

import java.time.LocalDate;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Entity class representing a customer.
 *
 * <p>
 * This class is mapped to the customer table
 * using JPA and Hibernate.
 * </p>
 */
@Getter
@Setter
@Entity
@Table(name = "customer")
public class Customer {

    /**
     * Unique ID of the customer.
     *
     * <p>
     * The ID is automatically generated by the database.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * First name of the customer.
     */
    private String firstName;

    /**
     * Last name of the customer.
     */
    private String lastName;

    /**
     * Date of birth of the customer.
     */
    private LocalDate dateOfBirth;

    /**
     * Mobile number of the customer.
     */
    private String mobile;

    /**
     * First address of the customer.
     */
    private String address1;

    /**
     * Second address of the customer.
     */
    private String address2;

    /**
     * Age of the customer.
     */
    private int age;

    /**
     * Gender of the customer.
     */
    private String gender;

    /**
     * Email address of the customer.
     */
    private String email;
}
